[package]
name = "sssd"
version = "1.0.1"
authors = ["hansan"]
edition = "2021"
license = "MIT"
description = "A simple way to let your app support like ./your_app start | stop | status | daemon."
repository = "https://github.com/funtoy/sssd"

[dependencies]
sysinfo = "0.29"